// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: scheduler.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on QuerySourceParam with the rules defined
// in the proto definition for this message. If any rules are violated, an
// error is returned.
func (m *QuerySourceParam) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for SourceId

	return nil
}

// QuerySourceParamValidationError is the validation error returned by
// QuerySourceParam.Validate if the designated constraints aren't met.
type QuerySourceParamValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QuerySourceParamValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QuerySourceParamValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QuerySourceParamValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QuerySourceParamValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QuerySourceParamValidationError) ErrorName() string { return "QuerySourceParamValidationError" }

// Error satisfies the builtin error interface
func (e QuerySourceParamValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQuerySourceParam.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QuerySourceParamValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QuerySourceParamValidationError{}

// Validate checks the field values on SourceInfo with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *SourceInfo) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for SourceId

	// no validation rules for Text

	return nil
}

// SourceInfoValidationError is the validation error returned by
// SourceInfo.Validate if the designated constraints aren't met.
type SourceInfoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SourceInfoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SourceInfoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SourceInfoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SourceInfoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SourceInfoValidationError) ErrorName() string { return "SourceInfoValidationError" }

// Error satisfies the builtin error interface
func (e SourceInfoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSourceInfo.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SourceInfoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SourceInfoValidationError{}
